name: Test and coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Install deps
        run: |
          sudo apt-get install -y libgpgme-dev libbtrfs-dev libdevmapper-dev
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - name: Run go test and generate coverage
        run: go test -v -race -coverprofile=coverage.out -covermode=atomic `go list ./... | grep -v /test`
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
